run:
  timeout: 2m # проект не большой, поэтому данного времени достаточно для проверки

linters: # подключаем линтеры
  enable:
    - errcheck # проверяет обработку ошибок
    - govet # анализирует потенциальные ошибки
    - staticcheck # ищет неиспользуемые переменные, функции, дублирующий код
    - gosec # проверяет уязвимости
    - revive # анализирует стиль, требует комментирование

issues: # предотвращает излишний спам из ошибок
  max-issues-per-linter: 10 # если 10 проблем, проверка останавливается
  max-same-issues: 3 # сокращает повтор однотипных ошибок до 3 первых (даже если они дальше есть по коду)

linters-settings: # отдельные настройки
  errcheck:
    check-blank: true # запрет игнорирования ошибок с помощью _
  revive:
    severity: warning # вместо ошибки по стилю выдает предупреждение
  gosec:
    excludes:
      - G104  # игнорировать ошибки пустого блока if err != nil {}